### ISSUE TITLE
Serialize/deserialize plain object

### ISSUE THREAD

**Issue by syabro** [mobxjs/serializr#34]
I've a simple mobx observable object and I've to use custom hack `custom((settings)=>toJS(settings), (settings)=>settings)`
 or I'll get error that settings is not primitive. Maybe I've missed something from the documentation?

My code:

```javascript
class SomeObject {
   ....
   @observable settings = {}
}

const SomeObjectSchema = {
  props: {
    settings: custom((settings)=>toJS(settings), (settings)=>settings),
  }
}

setDefaultModelSchema(SomeObject, SomeObjectSchema)
```

**Comment by aap82** [comment]
you need a schema for the settings object, with it's properties defined.  

also, for you SomeObject class, since it doesn't have any properties, it won't be observed (https://mobx.js.org/refguide/object.html).

> Some things to keep in mind when making objects observable:
> 
> When passing objects through observable, only the properties that exist at the time of making the object observable will be observable. Properties that are added to the object at a later time won't become observable, unless extendObservable is used.

That said, this is the pattern I'm using now. I'm not sure if it's acceptable practice (I'm not a developer/programmer of any kind), but  it seems to work for me:

```
class TestClass
  constructor: ->
    extendObservable @, getDefaultModelSchema(TestClass).observables

myTestClassSchema =
  factory: (-> new TestClass)
  props:
    id: yes
    title: yes
    name: yes
    test1: yes
    test2: yes
    isAuthenticated: yes
  observables:
    title: ''
    name: ''
    test1: 0
    test2: ''

setDefaultModelSchema(TestClass, myTestClassSchema)
module.exports = myTestClassSchema
```
